package com.propositodigital.quake.quakeparse.models;

public enum TypesOfDeath {
	// REPRESENTA TODOS OS TIPOS DE MORTE QUE UM JOGADOR PODE SOFRER
	
		MOD_TRIGGER_HURT, 	// MORTE POR FERIMENTO SEGUIDO DE QUEDA.
		MOD_ROCKET_SPLASH,  // MORTE POR ARMA ROCKETSPLASH.
		MOD_FALLING, 		// MORTE POR QUEDA.
		MOD_ROCKET,			// MORTE POR ARMA ROCKET.
		MOD_RAILGUN,		// MORTE POR ARMA RAILGUN.
		MOD_MACHINEGUN,		// MORTE POR ARMA MACHINEGUN.
		MOD_SHOTGUN,		// MORTE POR ARMA SHOTGUN.
		MOD_CRUSH,			// MORTE POR ESMAGAMENTO.
		MOD_BFG,			// MORTE POR ARMA BFG.
		MOD_BFG_SPLASH,		// MORTE POR ARMA BFGSPLASH.
		MOD_TELEFRAG		// MORTE POR ARMA TELEFRAG.
}
